name: Run Python Script

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 15 minutes (UTC)
  workflow_dispatch:         # Allows manual run too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python PDchecker.py
